"""Item cost added

Revision ID: 467d781f01e1
Revises: 7273d9901bd2
Create Date: 2021-07-20 17:23:52.726326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467d781f01e1'
down_revision = '7273d9901bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'cost')
    # ### end Alembic commands ###
